
# To consume this file in a Python program:
#
#     from gDSIr import *
#
# Start of gDS include file ...
#
# Generated by gDSCompile from gDSIr.dd (-O: ordinary list/dict storage)

import json
import sys
#
# Table dsTable
#
dsTable_Name = []
dsTable_Name_2Ref = {}
dsTable_dsVariable_Refs = []
dsTable_Type = []
dsTable_DefineLineNumber = []
dsTable_DefineLineIndex = []
dsTable_EndLineNumber = []
dsTable_EndLineIndex = []
dsTable_RowStatus = []

#
# Table dsVariable
#
dsVariable_Name = []
dsVariable_Name_2Ref = {}
dsVariable_BareName = []
dsVariable_dsTable_Ref = []
dsVariable_Type = []
dsVariable_OptionalValueCount = []
dsVariable_OptionalValue1 = []
dsVariable_OptionalValue2 = []
dsVariable_OptionalValue3 = []
dsVariable_LineNumber = []
dsVariable_LineIndex = []
dsVariable_RowStatus = []


#
# dsTable_AddARow
#
def dsTable_AddARow(
    _dsTable_Name,
    _dsTable_dsVariable_Refs,
    _dsTable_Type,
    _dsTable_DefineLineNumber,
    _dsTable_DefineLineIndex,
    _dsTable_EndLineNumber,
    _dsTable_EndLineIndex,
    _dsTable_RowStatus=None,
):
    if _dsTable_Name in dsTable_Name_2Ref:
        raise ValueError('Duplicate index key in dsTable_Name_2Ref: ' + repr(_dsTable_Name))
    dsTable_Name.append(_dsTable_Name)
    dsTable_dsVariable_Refs.append(_dsTable_dsVariable_Refs)
    dsTable_Type.append(_dsTable_Type)
    dsTable_DefineLineNumber.append(_dsTable_DefineLineNumber)
    dsTable_DefineLineIndex.append(_dsTable_DefineLineIndex)
    dsTable_EndLineNumber.append(_dsTable_EndLineNumber)
    dsTable_EndLineIndex.append(_dsTable_EndLineIndex)
    thisRef = len(dsTable_RowStatus)
    dsTable_Name_2Ref[dsTable_Name[thisRef]] = thisRef
    dsTable_RowStatus.append(_dsTable_RowStatus)
    return thisRef

#
# dsVariable_AddARow
#
def dsVariable_AddARow(
    _dsVariable_Name,
    _dsVariable_dsTable_Ref,
    _dsVariable_Type,
    _dsVariable_OptionalValueCount,
    _dsVariable_OptionalValue1,
    _dsVariable_OptionalValue2,
    _dsVariable_OptionalValue3,
    _dsVariable_LineNumber,
    _dsVariable_LineIndex,
    _dsVariable_BareName=None,
    _dsVariable_RowStatus=None,
):
    if _dsVariable_Name in dsVariable_Name_2Ref:
        raise ValueError('Duplicate index key in dsVariable_Name_2Ref: ' + repr(_dsVariable_Name))
    dsVariable_Name.append(_dsVariable_Name)
    dsVariable_BareName.append(_dsVariable_BareName)
    dsVariable_dsTable_Ref.append(_dsVariable_dsTable_Ref)
    dsVariable_Type.append(_dsVariable_Type)
    dsVariable_OptionalValueCount.append(_dsVariable_OptionalValueCount)
    dsVariable_OptionalValue1.append(_dsVariable_OptionalValue1)
    dsVariable_OptionalValue2.append(_dsVariable_OptionalValue2)
    dsVariable_OptionalValue3.append(_dsVariable_OptionalValue3)
    dsVariable_LineNumber.append(_dsVariable_LineNumber)
    dsVariable_LineIndex.append(_dsVariable_LineIndex)
    thisRef = len(dsVariable_RowStatus)
    dsVariable_Name_2Ref[dsVariable_Name[thisRef]] = thisRef
    dsVariable_RowStatus.append(_dsVariable_RowStatus)
    return thisRef
#
# Print values out for table 'dsTable'
#
def dsTable_DumpRows(rangeListToDump = None, outFile = sys.stdout):

    print(f'**************', file=outFile)
    print(f'**************', file=outFile)
    print('    Table %s has %d entries' % ('dsTable', len(dsTable_RowStatus)), file=outFile)
    print(f'**************', file=outFile)
    print(f'**************', file=outFile)
    print(f'', file=outFile)

    for rowRef in range(0, len(dsTable_RowStatus)):
        if (rangeListToDump is None) or (rowRef in rangeListToDump):
            print('    Row reference = %d' % (rowRef), file=outFile)
            print('    %30s = %10s' % ('dsTable_Name', dsTable_Name[rowRef]), file=outFile)
            _refs_dsTable_dsVariable_Refs = dsTable_dsVariable_Refs[rowRef]
            if not _refs_dsTable_dsVariable_Refs:
                print('    %30s = %10s  (%30s)' % ('dsTable_dsVariable_Refs', _refs_dsTable_dsVariable_Refs, ''), file=outFile)
            else:
                _deref_names_dsTable_dsVariable_Refs = []
                for _deref_name_dsTable_dsVariable_Refs in _refs_dsTable_dsVariable_Refs:
                    if _deref_name_dsTable_dsVariable_Refs is None:
                        _deref_names_dsTable_dsVariable_Refs.append('None(???)')
                    else:
                        try:
                            _n = dsVariable_Name[_deref_name_dsTable_dsVariable_Refs]
                        except IndexError:
                            _deref_names_dsTable_dsVariable_Refs.append('???')
                        else:
                            _deref_names_dsTable_dsVariable_Refs.append('???' if _n is None else _n)
                print('    %30s = %10s  (%30s)' % ('dsTable_dsVariable_Refs', _refs_dsTable_dsVariable_Refs, ', '.join(str(n) for n in _deref_names_dsTable_dsVariable_Refs)), file=outFile)
            print('    %30s = %10s' % ('dsTable_Type', dsTable_Type[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsTable_DefineLineNumber', dsTable_DefineLineNumber[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsTable_DefineLineIndex', dsTable_DefineLineIndex[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsTable_EndLineNumber', dsTable_EndLineNumber[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsTable_EndLineIndex', dsTable_EndLineIndex[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsTable_RowStatus', dsTable_RowStatus[rowRef]), file=outFile)
            if dsTable_Name_2Ref[dsTable_Name[rowRef]] != rowRef:
                raise ValueError('Bad index value in dsTable_Name_2Ref; value = ' + str(dsTable_Name[rowRef]))
            else:
                print(f"                    Good index value in dsTable_Name_2Ref[{dsTable_Name[rowRef]!r}]: {rowRef}", file=outFile)
            print('', file=outFile)

    return
#
# Print values out for table 'dsVariable'
#
def dsVariable_DumpRows(rangeListToDump = None, outFile = sys.stdout):

    print(f'**************', file=outFile)
    print(f'**************', file=outFile)
    print('    Table %s has %d entries' % ('dsVariable', len(dsVariable_RowStatus)), file=outFile)
    print(f'**************', file=outFile)
    print(f'**************', file=outFile)
    print(f'', file=outFile)

    for rowRef in range(0, len(dsVariable_RowStatus)):
        if (rangeListToDump is None) or (rowRef in rangeListToDump):
            print('    Row reference = %d' % (rowRef), file=outFile)
            print('    %30s = %10s' % ('dsVariable_Name', dsVariable_Name[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsVariable_BareName', dsVariable_BareName[rowRef]), file=outFile)
            _deref_dsVariable_dsTable_Ref = dsVariable_dsTable_Ref[rowRef]
            if _deref_dsVariable_dsTable_Ref is None:
                _deref_name_dsVariable_dsTable_Ref = 'None(???)'
            else:
                try:
                    _deref_name_dsVariable_dsTable_Ref = dsTable_Name[_deref_dsVariable_dsTable_Ref]
                except IndexError:
                    _deref_name_dsVariable_dsTable_Ref = '???'
                else:
                    if _deref_name_dsVariable_dsTable_Ref is None:
                        _deref_name_dsVariable_dsTable_Ref = '???'
            print('    %30s = %10s  (%30s)' % ('dsVariable_dsTable_Ref', _deref_dsVariable_dsTable_Ref, _deref_name_dsVariable_dsTable_Ref), file=outFile)
            print('    %30s = %10s' % ('dsVariable_Type', dsVariable_Type[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsVariable_OptionalValueCount', dsVariable_OptionalValueCount[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsVariable_OptionalValue1', dsVariable_OptionalValue1[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsVariable_OptionalValue2', dsVariable_OptionalValue2[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsVariable_OptionalValue3', dsVariable_OptionalValue3[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsVariable_LineNumber', dsVariable_LineNumber[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsVariable_LineIndex', dsVariable_LineIndex[rowRef]), file=outFile)
            print('    %30s = %10s' % ('dsVariable_RowStatus', dsVariable_RowStatus[rowRef]), file=outFile)
            if dsVariable_Name_2Ref[dsVariable_Name[rowRef]] != rowRef:
                raise ValueError('Bad index value in dsVariable_Name_2Ref; value = ' + str(dsVariable_Name[rowRef]))
            else:
                print(f"                    Good index value in dsVariable_Name_2Ref[{dsVariable_Name[rowRef]!r}]: {rowRef}", file=outFile)
            print('', file=outFile)

    return

#
# dsTable_DeleteRows
#
#
# Delete rows in table 'dsTable'.
# deleteMethod: "allRows" | "rowStatusValueToDelete" | "rowReferencesToDelete".
# selectorValue: None (ignored for allRows), a RowStatus value, or a list of row refs.
# Does not call ApplyRAL; use <owning>_ApplyRALTo_dsTable_Ref or _Refs afterward.
# Forward pass fills _ral: old row index -> new 'compacted' index, or None if deleted.
# Reverse pass removes rows where _ral[old] is None. Returns the RAL.
#
def dsTable_DeleteRows(deleteMethod, selectorValue = None):
    if deleteMethod not in ("allRows", "rowStatusValueToDelete", "rowReferencesToDelete"):
        raise ValueError(
            "dsTable_DeleteRows: deleteMethod must be 'allRows', 'rowStatusValueToDelete', or 'rowReferencesToDelete', got "
            + repr(deleteMethod)
        )
    if deleteMethod == "rowReferencesToDelete" and selectorValue is None:
        raise ValueError(
            "dsTable_DeleteRows: rowReferencesToDelete requires selectorValue (list of row refs)"
        )
    _n = len(dsTable_RowStatus)
    _ral = []
    _next_new = 0
    if deleteMethod == "rowReferencesToDelete":
        _dset = set(selectorValue)
    for rowRef in range(_n):
        if deleteMethod == "allRows":
            _delete = True
        elif deleteMethod == "rowStatusValueToDelete":
            _delete = (dsTable_RowStatus[rowRef] == selectorValue)
        else:
            _delete = (rowRef in _dset)
        if _delete:
            _ral.append(None)
        else:
            _ral.append(_next_new)
            _next_new += 1

    for rowRef in range(_n - 1, -1, -1):
        if _ral[rowRef] is None:
            del dsTable_Name[rowRef]
            del dsTable_dsVariable_Refs[rowRef]
            del dsTable_Type[rowRef]
            del dsTable_DefineLineNumber[rowRef]
            del dsTable_DefineLineIndex[rowRef]
            del dsTable_EndLineNumber[rowRef]
            del dsTable_EndLineIndex[rowRef]
            del dsTable_RowStatus[rowRef]
        else:
            pass

    dsTable_Name_2Ref.clear()
    for rowRef in range(len(dsTable_RowStatus)):
        dsTable_Name_2Ref[dsTable_Name[rowRef]] = rowRef

    return _ral


#
# dsVariable_DeleteRows
#
#
# Delete rows in table 'dsVariable'.
# deleteMethod: "allRows" | "rowStatusValueToDelete" | "rowReferencesToDelete".
# selectorValue: None (ignored for allRows), a RowStatus value, or a list of row refs.
# Does not call ApplyRAL; use <owning>_ApplyRALTo_dsVariable_Ref or _Refs afterward.
# Forward pass fills _ral: old row index -> new 'compacted' index, or None if deleted.
# Reverse pass removes rows where _ral[old] is None. Returns the RAL.
#
def dsVariable_DeleteRows(deleteMethod, selectorValue = None):
    if deleteMethod not in ("allRows", "rowStatusValueToDelete", "rowReferencesToDelete"):
        raise ValueError(
            "dsVariable_DeleteRows: deleteMethod must be 'allRows', 'rowStatusValueToDelete', or 'rowReferencesToDelete', got "
            + repr(deleteMethod)
        )
    if deleteMethod == "rowReferencesToDelete" and selectorValue is None:
        raise ValueError(
            "dsVariable_DeleteRows: rowReferencesToDelete requires selectorValue (list of row refs)"
        )
    _n = len(dsVariable_RowStatus)
    _ral = []
    _next_new = 0
    if deleteMethod == "rowReferencesToDelete":
        _dset = set(selectorValue)
    for rowRef in range(_n):
        if deleteMethod == "allRows":
            _delete = True
        elif deleteMethod == "rowStatusValueToDelete":
            _delete = (dsVariable_RowStatus[rowRef] == selectorValue)
        else:
            _delete = (rowRef in _dset)
        if _delete:
            _ral.append(None)
        else:
            _ral.append(_next_new)
            _next_new += 1

    for rowRef in range(_n - 1, -1, -1):
        if _ral[rowRef] is None:
            del dsVariable_Name[rowRef]
            del dsVariable_BareName[rowRef]
            del dsVariable_dsTable_Ref[rowRef]
            del dsVariable_Type[rowRef]
            del dsVariable_OptionalValueCount[rowRef]
            del dsVariable_OptionalValue1[rowRef]
            del dsVariable_OptionalValue2[rowRef]
            del dsVariable_OptionalValue3[rowRef]
            del dsVariable_LineNumber[rowRef]
            del dsVariable_LineIndex[rowRef]
            del dsVariable_RowStatus[rowRef]
        else:
            pass

    dsVariable_Name_2Ref.clear()
    for rowRef in range(len(dsVariable_RowStatus)):
        dsVariable_Name_2Ref[dsVariable_Name[rowRef]] = rowRef

    return _ral


#
# dsTable_ApplyRALTo_dsVariable_Refs
#
#
# Apply a RAL to references in dsTable column 'dsTable_dsVariable_Refs' to rows in dsVariable.
# No deleteAction: each list entry pointing at a deleted destination row is removed;
# surviving destination rows are reindexed via the RAL.
#
def dsTable_ApplyRALTo_dsVariable_Refs(RAL):
    if RAL is None:
        raise ValueError(
            "dsTable_ApplyRALTo_dsVariable_Refs: requires RAL"
        )
    for rowRef in range(len(dsTable_RowStatus)):
        _refs = dsTable_dsVariable_Refs[rowRef]
        if not _refs:
            continue
        for _ri in range(len(_refs) - 1, -1, -1):
            _v = _refs[_ri]
            if _v is None:
                continue
            _adj = RAL[_v]
            if _adj is not None:
                _refs[_ri] = _adj
            else:
                del _refs[_ri]


#
# dsVariable_ApplyRALTo_dsTable_Ref
#
#
# Apply a RAL to references in dsVariable column 'dsVariable_dsTable_Ref' to rows in dsTable.
#
def dsVariable_ApplyRALTo_dsTable_Ref(RAL, deleteAction):
    if RAL is None:
        raise ValueError(
            "dsVariable_ApplyRALTo_dsTable_Ref: requires RAL"
        )
    if deleteAction not in ("setRefToNone", "deleteRow"):
        raise ValueError(
            "dsVariable_ApplyRALTo_dsTable_Ref: deleteAction must be 'setRefToNone' or 'deleteRow', got "
            + repr(deleteAction)
        )
    _drows = []
    for rowRef in range(len(dsVariable_RowStatus)):
        _v = dsVariable_dsTable_Ref[rowRef]
        if _v is None:
            continue
        _adj = RAL[_v]
        if _adj is not None:
            dsVariable_dsTable_Ref[rowRef] = _adj
        else:
            if deleteAction == "setRefToNone":
                dsVariable_dsTable_Ref[rowRef] = None
            else:
                _drows.append(rowRef)
    if _drows:
        _dset = set(_drows)
        _n0 = len(dsVariable_RowStatus)
        _ralB = []
        _nn = 0
        for rowRef in range(_n0):
            if rowRef in _dset:
                _ralB.append(None)
            else:
                _ralB.append(_nn)
                _nn += 1
        for rowRef in sorted(_drows, reverse=True):
            del dsVariable_Name[rowRef]
            del dsVariable_BareName[rowRef]
            del dsVariable_dsTable_Ref[rowRef]
            del dsVariable_Type[rowRef]
            del dsVariable_OptionalValueCount[rowRef]
            del dsVariable_OptionalValue1[rowRef]
            del dsVariable_OptionalValue2[rowRef]
            del dsVariable_OptionalValue3[rowRef]
            del dsVariable_LineNumber[rowRef]
            del dsVariable_LineIndex[rowRef]
            del dsVariable_RowStatus[rowRef]
        dsVariable_Name_2Ref.clear()
        for rowRef in range(len(dsVariable_RowStatus)):
            dsVariable_Name_2Ref[dsVariable_Name[rowRef]] = rowRef



#
# dsTable_WriteToFile / dsTable_ReadFromFile
#
#
# Write table 'dsTable' to JSON file *filespec* (columns and index dicts).
#
def dsTable_WriteToFile(filespec):
    with open(filespec, "w", encoding="utf-8") as _f:
        json.dump(
            {
                "table": 'dsTable',
                "columns": {
            "dsTable_Name": list(dsTable_Name),
            "dsTable_dsVariable_Refs": [list(_row) for _row in dsTable_dsVariable_Refs],
            "dsTable_Type": list(dsTable_Type),
            "dsTable_DefineLineNumber": list(dsTable_DefineLineNumber),
            "dsTable_DefineLineIndex": list(dsTable_DefineLineIndex),
            "dsTable_EndLineNumber": list(dsTable_EndLineNumber),
            "dsTable_EndLineIndex": list(dsTable_EndLineIndex),
            "dsTable_RowStatus": list(dsTable_RowStatus),
                },
                "indexes": {
            "dsTable_Name_2Ref": dict(dsTable_Name_2Ref),
                },
            },
            _f,
            indent=2,
        )

#
# Read table 'dsTable' from JSON file *filespec* (replaces current column/index data).
#
def dsTable_ReadFromFile(filespec):
    with open(filespec, "r", encoding="utf-8") as _f:
        _data = json.load(_f)
    _cols = _data.get("columns", {})
    del dsTable_Name[:]
    dsTable_Name.extend(_cols.get('dsTable_Name', []))
    del dsTable_dsVariable_Refs[:]
    for _row in _cols.get('dsTable_dsVariable_Refs', []):
        dsTable_dsVariable_Refs.append(list(_row))
    del dsTable_Type[:]
    dsTable_Type.extend(_cols.get('dsTable_Type', []))
    del dsTable_DefineLineNumber[:]
    dsTable_DefineLineNumber.extend(_cols.get('dsTable_DefineLineNumber', []))
    del dsTable_DefineLineIndex[:]
    dsTable_DefineLineIndex.extend(_cols.get('dsTable_DefineLineIndex', []))
    del dsTable_EndLineNumber[:]
    dsTable_EndLineNumber.extend(_cols.get('dsTable_EndLineNumber', []))
    del dsTable_EndLineIndex[:]
    dsTable_EndLineIndex.extend(_cols.get('dsTable_EndLineIndex', []))
    del dsTable_RowStatus[:]
    dsTable_RowStatus.extend(_cols.get('dsTable_RowStatus', []))
    # Rebuild indexes from columns; JSON object keys are strings and may not
    # match in-memory key types (e.g. float timestamps in defineIndexOneRef).
    dsTable_Name_2Ref.clear()
    for rowRef in range(len(dsTable_RowStatus)):
        dsTable_Name_2Ref[dsTable_Name[rowRef]] = rowRef


#
# dsVariable_WriteToFile / dsVariable_ReadFromFile
#
#
# Write table 'dsVariable' to JSON file *filespec* (columns and index dicts).
#
def dsVariable_WriteToFile(filespec):
    with open(filespec, "w", encoding="utf-8") as _f:
        json.dump(
            {
                "table": 'dsVariable',
                "columns": {
            "dsVariable_Name": list(dsVariable_Name),
            "dsVariable_BareName": list(dsVariable_BareName),
            "dsVariable_dsTable_Ref": list(dsVariable_dsTable_Ref),
            "dsVariable_Type": list(dsVariable_Type),
            "dsVariable_OptionalValueCount": list(dsVariable_OptionalValueCount),
            "dsVariable_OptionalValue1": list(dsVariable_OptionalValue1),
            "dsVariable_OptionalValue2": list(dsVariable_OptionalValue2),
            "dsVariable_OptionalValue3": list(dsVariable_OptionalValue3),
            "dsVariable_LineNumber": list(dsVariable_LineNumber),
            "dsVariable_LineIndex": list(dsVariable_LineIndex),
            "dsVariable_RowStatus": list(dsVariable_RowStatus),
                },
                "indexes": {
            "dsVariable_Name_2Ref": dict(dsVariable_Name_2Ref),
                },
            },
            _f,
            indent=2,
        )

#
# Read table 'dsVariable' from JSON file *filespec* (replaces current column/index data).
#
def dsVariable_ReadFromFile(filespec):
    with open(filespec, "r", encoding="utf-8") as _f:
        _data = json.load(_f)
    _cols = _data.get("columns", {})
    del dsVariable_Name[:]
    dsVariable_Name.extend(_cols.get('dsVariable_Name', []))
    del dsVariable_BareName[:]
    dsVariable_BareName.extend(_cols.get('dsVariable_BareName', []))
    del dsVariable_dsTable_Ref[:]
    dsVariable_dsTable_Ref.extend(_cols.get('dsVariable_dsTable_Ref', []))
    del dsVariable_Type[:]
    dsVariable_Type.extend(_cols.get('dsVariable_Type', []))
    del dsVariable_OptionalValueCount[:]
    dsVariable_OptionalValueCount.extend(_cols.get('dsVariable_OptionalValueCount', []))
    del dsVariable_OptionalValue1[:]
    dsVariable_OptionalValue1.extend(_cols.get('dsVariable_OptionalValue1', []))
    del dsVariable_OptionalValue2[:]
    dsVariable_OptionalValue2.extend(_cols.get('dsVariable_OptionalValue2', []))
    del dsVariable_OptionalValue3[:]
    dsVariable_OptionalValue3.extend(_cols.get('dsVariable_OptionalValue3', []))
    del dsVariable_LineNumber[:]
    dsVariable_LineNumber.extend(_cols.get('dsVariable_LineNumber', []))
    del dsVariable_LineIndex[:]
    dsVariable_LineIndex.extend(_cols.get('dsVariable_LineIndex', []))
    del dsVariable_RowStatus[:]
    dsVariable_RowStatus.extend(_cols.get('dsVariable_RowStatus', []))
    # Rebuild indexes from columns; JSON object keys are strings and may not
    # match in-memory key types (e.g. float timestamps in defineIndexOneRef).
    dsVariable_Name_2Ref.clear()
    for rowRef in range(len(dsVariable_RowStatus)):
        dsVariable_Name_2Ref[dsVariable_Name[rowRef]] = rowRef

